#Conexão com o banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/aula03
spring.datasource.username=postgres
spring.datasource.password=02092020

#DDL - como o hibernate trata a estrutura do banco de dados
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true

#Sql no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Dialeto do banco de dados
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.jackson.deserialization.fail-on-unknown-properties=true

#Nome da aplicação
spring.application.name=Aula03
