spring.application.name=Aula06

spring.datasource.url=jdbc:postgresql://localhost:5432/aula06
spring.datasource.username=postgres
spring.datasource.password=02092020
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
